set nocompatible
filetype plugin on

set scrolloff=7
syntax on
set mouse=a

" sane tab behaviour
set expandtab
set smarttab
set tabstop=4
set shiftwidth=4

" enable line numbers
set number

" disable bells
set noerrorbells
set novisualbell

" don't continue comment in new line
set formatoptions-=ro

" keybindings
" move selected line
inoremap <A-Down> <Esc>:m .+1<CR>==gi
inoremap <A-UP> <Esc>:m .-2<CR>==gi

nnoremap <CR> o<Esc>
nnoremap <BS> X

" unbind arrow keys
"noremap <Up> <Nop>
"noremap <Down> <Nop>
"inoremap <Left> <Nop>
"noremap <Right> <Nop>
"inoremap <Up> <Nop>
"inoremap <Down> <Nop>
"inoremap <Left> <Nop>
"inoremap <Right> <Nop>
"vnoremap <Up> <Nop>
"vnoremap <Down> <Nop>
"vnoremap <Left> <Nop>
"vnoremap <Right> <Nop>

" unbind q
noremap q :q
