source ~/.local/bin/antigen.zsh
antigen use oh-my-zsh
antigen bundle z
antigen bundle git
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle djui/alias-tips
antigen theme denysdovhan/spaceship-prompt
antigen apply

export SPACESHIP_PROMPT_ADD_NEWLINE=false
export SPACESHIP_DIR_TRUNC=5
export ZSH_PLUGINS_ALIAS_TIPS_EXCLUDES='_ git'

export PATH=~/.local/bin:/snap/bin:$PATH
export LANG=C

# colored manpages
export LESS_TERMCAP_mb=$'\C-[[1;32m'
export LESS_TERMCAP_md=$'\C-[[1;32m'
export LESS_TERMCAP_me=$'\C-[[0m'
export LESS_TERMCAP_se=$'\C-[[0m'
export LESS_TERMCAP_so=$'\C-[[01;33m'
export LESS_TERMCAP_ue=$'\C-[[0m'
export LESS_TERMCAP_us=$'\C-[[1;4;31m'

source ~/.dotfiles/aliases.zsh
source ~/.dotfiles/functions.zsh
